pvc:
  storageClassName: netapp-file

mysql:
  pvc:
    storageClassName: netapp-file
  pv:
    #example: /trident_default_mysql_pv_claim_cb63e_copy
    path: /trident_default_mysql_pv_claim_cb63e_copy
    #example: 172.16.0.10
    server: 172.16.0.7



